### ISSUE TITLE
[epic] create v1 of save and load 3dstreet scenes

### ISSUE THREAD

**Issue by kfarr** [3DStreet/3dstreet-editor#203]
This continues to build on the branch https://github.com/3DStreet/3dstreet-editor/tree/feature-firebase-save-load to add all features related to save and load 3DStreet scenes. All tickets should be a PR into this `feature-firebase-save-load` branch, NOT a PR into `master`.

On the backend Firebase Firestore seems like the best solution + the Firestore JS SDK we're already using.

## Goal
Create a new 3DStreet scene or modify an imported scene like https://3dstreet.app#https://streetmix.net/kfarr/3/
Then save this scene as a new scene document in the firestore cloud
The user should be able to load the scene again for the given UUID

### All of Save / Load key tasks, starting with highest priority:

- [x] Login / Access - v1 done - https://github.com/3DStreet/3dstreet-editor/issues/169
- [x] Open Scene Given Path to JSON Scene - Client Side - https://github.com/3DStreet/3dstreet-editor/issues/199
- [x] Profile View / Logout - https://github.com/3DStreet/3dstreet-editor/issues/204
- [x] Zade - New save menu - https://github.com/3DStreet/3dstreet-editor/issues/210
- [x] KF - Feature branch housekeeping - https://github.com/3DStreet/3dstreet-editor/issues/232
- [x] Zade - Save New Scene with UUID - https://github.com/3DStreet/3dstreet-editor/issues/211
- [x] AG - Error / Success Messages (Foundation) - https://github.com/3DStreet/3dstreet/issues/317
- [x] KF - Open Scene Given Scene UUID - Server Side - https://github.com/3DStreet/3dstreet-editor/issues/213
- [x] Zade - Create production / local environments - https://github.com/3DStreet/3dstreet-editor/issues/228
- [x] AG - Add Error / Success Messages to Editor - https://github.com/3DStreet/3dstreet-editor/pull/241 maybe use this simpler version instead: https://github.com/3DStreet/3dstreet-editor/pull/254
- [x] Zade - Open Modal listing Scenes Owned By Me - https://github.com/3DStreet/3dstreet-editor/issues/222 -- See outstanding issues here: https://github.com/3DStreet/3dstreet-editor/pull/244
- [x] Zade - New sign in with google button #251 
- [x] Zade - createTimestamp and updateTimestamp https://github.com/3DStreet/3dstreet-editor/issues/248
- [x] Zade - Save Scene after opening Owned Scene UUID - https://github.com/3DStreet/3dstreet-editor/issues/247
- [x] Zade - Remove `uuid` field if we can https://github.com/3DStreet/3dstreet-editor/issues/260
- [x] KF - "Save as" when editing a scene not owned by me #250
- [x] AG - Fix save / load issues - intersections: #255  
- [x] KF - metadata component - https://github.com/3DStreet/3dstreet/issues/335
- [x] Zade - My Scenes and Community Scenes tab - #249
- [x] KF - sceneId incorrect in url path of scene opened in modal https://github.com/3DStreet/3dstreet-editor/issues/279
- [x] KF - sceneId not persisted when using editor, resulting in save as instead of save https://github.com/3DStreet/3dstreet-editor/issues/275
- [x] KF - Update scene graph panel after loading 3dstreet json scene from open modal #267
- [x] Zade - Investigation ticket - bundle size is 1.52MB on `feature-firebase-save-load` branch https://github.com/3DStreet/3dstreet-editor/issues/245
- [x] AG - Fix save / load issue - mapbox: #257 
- [x] KF - More deployment housekeeping - #242 and #243 
- [x] #282
- [x] remove user console log
- [x] Ensure new production keys have been rotated and are saved like the others
- [x] Deploy
- [x] Install mailchimp on production server
- [x] KF - MERGE #230

### Firestore things
The default firebase firestore ID is not a UUID, it is something different. So we will need to make sure to provide a UUID when first saving the file.

To save a new file, such as one imported from streetmix like 3dstreet.app#https://streetmix.net/kfarr/3/, use firestore `set` with a json document ("document-shaped data" in one comment I saw). The collection name we can use for scenes is "scenes"

The document format could be something like
```
{
  title: "string",
  version: "1.0",
  author: authorID,  // only this user is permitted to modify this file 
  data: { scene nodes }
}
```

### Accessing Scenes - Public API
For this milestone scenes are accessed via a public JSON URL loaded by the 3dstreet.app as follows:
* https://3dstreet.app/scenes/[UUID].json will load the json file describing the scene. This can be served using firebase cloud function to fetch the json value and send it back out using permissive cors

Firebase Cloud Function
- for JSON plaintext HTTP get use rewrites
- `**/*.json` rewrites syntax for all json files match
- returns contents of document for UUID
- Path: /scenes/[UUID].json -> permissive CORS
- initial load of a scene is always from public json, even if auth'ed and owner

https://3dstreet.app/#/scenes/[UUID].json will load the 3d scene for the end-user

## Accessing Scenes - SDK
SDK - for a given scene UUID provided in the json in the url in format /scenes/UUID/ use the sdk to fetch the json representing the scene. It looks like for saving the sdk is required.

```mermaid
flowchart TD
    A(New or Imported Street from streetmix or gallery) --> B
    B(User makes changes in Editor and says, 'I want to save!') --> C
    C(Click Save Button) --> D
    D{Is user logged in?} --> |Yes| E
    D --> |No|F(Account Sign In) --> E
    E(Save) --> G
    G(New UUID) --> H
    H(Save scene JSON to UUID Blob) --> I
    I(Forward URL to new scene 3dstreet.app/#/scene/UUID.json)
```

Save cases to consider:
1) import -> save (new)
2) open saved file, unauthed -> save
3) open saved file, authed -> save
4) open saved file, unauthed -> save as...
5) open saved file, authed -> save as...

out of scope:
- Q) how is scene name considered during save process? A) out of scope, scene name doesn't exist yet
- Q) what is the UX / UI to encourage a new user to remix a street they are currently editing but not saved?
