### ISSUE TITLE
[epic] v2 of save / share scenes

### ISSUE THREAD

**Issue by kfarr** [3DStreet/3dstreet-editor#259]
As a user I can open community scenes or import a streetmix street, modify the scene, name it, then save and share the scenes URL directly with other people.

(This is a followup to v1 open/save scenes epic 3DStreet/3dstreet-editor#203)

## Tasks
- [x] KF - add metadata component for scene title https://github.com/3DStreet/3dstreet/issues/335
- [x] KF / AG - notify improvements https://github.com/3DStreet/3dstreet/issues/333
- [x] AG - do not save extraneous json https://github.com/3DStreet/3dstreet/issues/344
- [x] KF 3DStreet/3dstreet-editor#294
- [x] Zade - open modal - add streetmix and json buttons 3DStreet/3dstreet-editor#263
- [x] Zade - open modal - not logged in state 3DStreet/3dstreet-editor#265
- [x] KF mailchimp integration for new users 3DStreet/3dstreet-editor#290
- [x] Zade - open modal - resize scene cards to 4:3 https://github.com/3DStreet/3dstreet-editor/issues/272
- [x] Zade - saving indicator https://github.com/3DStreet/3dstreet-editor/issues/287
- [x] Zade - share modal updates 3DStreet/3dstreet-editor#262
- [x] AG - refresh scene graph when loading json file https://github.com/3DStreet/3dstreet-editor/issues/285
- [x] KF - regression, metadata component https://github.com/3DStreet/3dstreet/issues/356
- [x] AG - display scene title in viewer https://github.com/3DStreet/3dstreet/issues/336
- [x] Zade - display and allow editing of scene title in editor  3DStreet/3dstreet-editor#261
- [x] Zade - set scene thumbnail from capture/share modal 3DStreet/3dstreet-editor#266
- [x] remove extra menu items KF 3DStreet/3dstreet-editor#303
- [x] Zade - loading spinner in open modal 3DStreet/3dstreet-editor#301
- [x] Do not create duplicates after remixing https://github.com/3DStreet/3dstreet-editor/issues/307
- [x] 3DStreet/3dstreet-editor#318
- [x] 3DStreet/3dstreet-editor#321
- [x] ~~Zade - open modal - default scene preview image when not available 3DStreet/3dstreet-editor#268~~
- [x] Zade - title edit followup fixes https://github.com/3DStreet/3dstreet-editor/issues/311
- [x] Zade - rename / delete from open modal 3DStreet/3dstreet-editor#305
- [x] Zade - Show remix button instead of save in some cases https://github.com/3DStreet/3dstreet-editor/issues/308
- [x] Zade - 3DStreet/3dstreet-editor#322
- [x] Zade - 3DStreet/3dstreet-editor#323
- [x] Zade - Infinite scroll 3DStreet/3dstreet-editor#304
- [x] Zade - fix build process -- production not working as expected https://github.com/3DStreet/3dstreet-editor/pull/346
- [x] AG - hide helper objects https://github.com/3DStreet/3dstreet-editor/issues/306
- [x] Zade - auto save thumbnail when saving scene 3DStreet/3dstreet-editor#264
- [x] KF - do a dev server deployment
- [x] KF - first, merge main into this branch
- [x] KF - then, merge this PR with main
- [x] KF - do a production server deployment
