### ISSUE TITLE
[epic] v3 of save / share scenes

### ISSUE THREAD

**Issue by kfarr** [3DStreet/3dstreet-editor#364]
As a user I can open community scenes or import a streetmix street, modify the scene, name it, then save and share the scenes URL directly with other people.

(This is a followup to v2 open/save scenes epic 3DStreet/3dstreet-editor#259)

## Business Goals
- [x] Test email sending - automatic after joining
- [x] Zade - Open community scenes route (featured scenes) when opening empty app https://github.com/3DStreet/3dstreet-editor/issues/299

## User Expectations
- [x] Zade - boolean property widget does not work as expected https://github.com/3DStreet/3dstreet-editor/issues/374
- [x] Zade https://github.com/3DStreet/3dstreet-editor/issues/371
- [x] always show duplicate / delete / component info https://github.com/3DStreet/3dstreet-editor/issues/362
- [x] Zade - after thumbnail set does not show in open modal 3DStreet/3dstreet-editor#375
- [x] 3DStreet/3dstreet-editor#377
- [x] AG? thumbnail not created in some cases 3DStreet/3dstreet-editor#351
- [x] AG? sometimes screenshot results in black image https://github.com/3DStreet/3dstreet-editor/issues/372
- [x] AG - use STREET global in Editor repo https://github.com/3DStreet/3dstreet/issues/390

Instrumentation:
- [x] Zade - fix google analytics loading https://github.com/3DStreet/3dstreet-editor/issues/390
- [x] Zade - Instrument top 2 metrics https://github.com/3DStreet/3dstreet-editor/issues/324

To defer for future 
* Zade - break up build file into smaller pieces https://github.com/3DStreet/3dstreet/issues/591
* create prod vs. dev server firebase target settings https://github.com/3DStreet/3dstreet-editor/issues/355
* generate GLB upon user request https://github.com/3DStreet/3dstreet/issues/592
* Teleport behavior should match editor + core https://github.com/3DStreet/3dstreet-editor/issues/313
* title not displaying when loading scene in new window from URL 3DStreet/3dstreet#577

**Comment by kfarr** [comment]
completed another epic, thanks @ViktoriaShurhot !
