### ISSUE TITLE
[epic] usability priority - draft

### ISSUE THREAD

**Issue by kfarr** [3DStreet/3dstreet-editor#399]
- [ ] - button to create blank scene (with new ID / new title)
- [ ] - create blank scene (with new ID / new title) prior to loading streetmix street
- [ ] - behavior after I click remix is unexpected -- it still says remix on button
- [ ] - ortho cam view incorrect aspect ratio upon resize
- [ ] - dropdown menu in object properties panel opens downward and descends below visible window; instead open upward
- [ ] - when click and drag to move entity position, upon release if hovering over another objet will select that object instead
- [ ] - object select hover bounding box area does not match for rotated streets https://github.com/3DStreet/3dstreet/issues/588
- [ ] - reference layers should not be selectable via hover - same as skybox
- [ ] - when clicking "save as..." should pop open the scene rename with default scene name "Copy of [previous title]"
- [x] 3DStreet/3dstreet-editor#405
- [ ] title not displaying when loading scene in new window from URL https://github.com/3DStreet/3dstreet/issues/577
- [ ] grab vs. select mode (ie turn on / off raycaster hover to select)
- [ ] xr teleport behavior should match editor + core https://github.com/3DStreet/3dstreet-editor/issues/313
